### ISSUE TITLE
Contextual keywords with custom lexer

### ISSUE THREAD

**Issue by jnicklas** [nikomatsakis/lalrpop#112]
I'm trying to write a parser for GraphQL with LALRPOP. Since GraphQL has some rather odd lexing rules I have to use a custom lexer. Unfortunately, GraphQL also uses contextual keywords _a lot_. I haven't been able to figure out how to get both a custom lexer and contextual keywords working with LALRPOP.

One thing I can do to work around this is define a rule which maps all keywords to their respective string, kind of like this:

``` rust
Identifier: &'input str = {
    "schema" => { "schema" },
    "query" => { "query" },
    "mutation" => { "mutation" },
    "type" => { "type" },
    "implements" => { "Implements" },
    "on" => { "on" },
    <value:"identifier"> => { value },
};
```

But this is very tedious, and it feels like there must be a better way.

**Comment by jnicklas** [comment]
The ideal would be to get the behaviour of the default lexer, where I can just use literals inline and not have to lex them separately at all.

**Comment by nikomatsakis** [comment]
@jnicklas the workaround you listed is what I have done when modeling contextual keywords, but it might indeed be nice to have this more as a "builtin" feature. Contextual keywords don't mesh well with the "lexer-parser" divide that LALRPOP is based on. :(

**Comment by nikomatsakis** [comment]
I guess I could imagine some sort of option that makes a "pseudo-terminal" identifier that is equal to a given set of other terminals. e.g. if you could say "let `identifier` by all terminals that match `r[a-zA-Z]+`" or something.

**Comment by nikomatsakis** [comment]
Closing in favor of #195
