### ISSUE TITLE
Regex ambiguity false positives with wildcard

### ISSUE THREAD

**Issue by willcrichton** [nikomatsakis/lalrpop#141]
The parser generator incorrectly finds ambiguities in unambiguous grammars that use two different regexes, one of which involves a wildcard, in the same nonterminal. Example:

```
grammar;
pub Foo: () = {
    r"a" => (),
    "(" r"." ")" => (),
};
```

This produces the output:
```
/Users/will/Code/rust/lalrtest/src/test.lalrpop:4:5: 
    4:8 error: ambiguity detected between the terminal `r#"a"#` and the terminal `r#"."#`
```

**Comment by kalouantonis** [comment]
I have the same issue with this snippet:

```
expr: LispVal = {
    // Autoquoted values
    number,
    string,
};

number: LispVal = {
    integer => LispVal::Integer(<>),
    double => LispVal::Decimal(<>),
};

integer: i64 = r"[-+]?\d+" => i64::from_str(<>).unwrap();
double: f64 = r"[-+]?\d+\.\d+" => f64::from_str(<>).unwrap();

string: LispVal = {
    "\"" <r".*"> "\"" => LispVal::String(String::from(<>)),
};
```

Gives this error:

```
error: ambiguity detected between the terminal `r#"[-+]?\\d+"#` and the terminal `r#".*"#`
```

Environment:

```
rustc: rustc 1.11.0 (9b21dcd6a 2016-08-15)
cargo: 0.12.0-nightly (6b98d1f 2016-07-04)
lalrpop (and utils): 0.12.0
OS: Debian 8.5.0 
```

**Comment by nikomatsakis** [comment]
@willcrichton this is actually behaving as expected (though I agree it could be improved). There are two things to understand here:

First, we match all terminals in a "pre-pass" before the parser operators ("lexing"). So, in other words, it doesn't matter where the terminals appear in the grammar. You just have to consider the terminals as a kind of list:

- `r"a"`
- `"("`
- `")"`
- `r"."`

Second, we give higher precedence to terminals that are not regular expressions (e.g., `"("`, `")"`), and then lower precedence to regular expressions `(r"a", r".")`. Within one precedence level, the terminals must not overlap. So, in this case, the `r"."` certainly overlaps with `r"a"`. 

You could change the `r"a"` to `"a"` and your example would be accepted, however as a consequence `"a"` would be considered a "keyword" and hence something like `(a)` would not parse.

To resolve this, one would do something like:

```
grammar;
pub Foo: () = {
    "a" => (),
    "(" ANY ")" => (),
};
ANY = { "a", r"." };
```

In general, though, if you need lexing that is aware of where you are in the grammar, you would be better off with a PEG-based parser generator (I have thought about adding a PEG mode to LALRPOP; maybe someday).

**Comment by nikomatsakis** [comment]
@kalouantonis the same applies in your example (an the same solution).

**Comment by nikomatsakis** [comment]
Closing in favor of https://github.com/nikomatsakis/lalrpop/issues/143

**Comment by willcrichton** [comment]
@nikomatsakis What should I do if I need both to be regexes? For example, I want to have an expression production that contains both strings and numbers:

```
grammar;

pub Expr: () = {
    r"[0-9]"+ => (),
    "'" r".*" "'" => ()
};
```

Is this not expressible with vanilla LALRPOP? Will I need to use an external lexer?

**Comment by nikomatsakis** [comment]
You could combine the the string into r"'.*'", no?

**Comment by nikomatsakis** [comment]
Though you probably want r#"'[^']'"
