### ISSUE TITLE
lalrpop from slice 

### ISSUE THREAD

**Issue by adjivas** [nikomatsakis/lalrpop#155]
For my first try with lalrpop, I have writted this [grammar file](https://github.com/adjivas/pty-shell-mode/blob/117ea12178c45a2e63f15ee041795955794044c3/src/input.lalrpop) for parse a terminal input from a **sized slice** limited at 12 such as `[libc::c_uchar; 12]` named _Operate_.

My question ares:
- The examples use a common constructor _parse_Something_ with `&'input str` type, with a slice, it's imply to use this constructor like undermentioned and with the possible cost to prepare a str. There is another solution like a second constructor?

``` rust
input::parse_Operate(unsafe {
        str::from_utf8_unchecked(&buf[..len])
      }).unwrap()
```
- My use of lalrpop is adapted?

**Comment by torkleyy** [comment]
What do you mean by

> with the possible cost to prepare a `str`

? AFAIK `str` is the cheapest string in rust. Also, the conversion you show above has no additional cost as you see in the [source code](https://doc.rust-lang.org/src/core/str/mod.rs.html#296-298).

**Comment by adjivas** [comment]
@torkleyy You are right!
Your citation of the Str source solves my issue.
Thank you.
