### ISSUE TITLE
Recursive descent parser defines public functions for states and actions

### ISSUE THREAD

**Issue by ravenexp** [nikomatsakis/lalrpop#163]
State functions are encapsulated in a nested module, but action functions are not.
Is there a specific reason to use public functions in the parser internals?

**Comment by nikomatsakis** [comment]
Hmm, I'm not sure why I made action functions public. It does seem like an oversight / mistake. To correct this would just be a matter of changing [the code in `action.rs` that invokes `write_pub_fn_header`](https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop/src/build/action.rs#L111); seems like we may need to add another helper, though, or a parameter to control whether the function is public.

**Comment by ravenexp** [comment]
I did this as an experiment, and everything seemed to work as usual. I hoped to measure some code size/performance advantages of hiding the state and action functions, but couldn't detect any...

**Comment by nikomatsakis** [comment]
@ravenexp still, a PR would be welcome =)

**Comment by ravenexp** [comment]
https://github.com/nikomatsakis/lalrpop/pull/222
