### ISSUE TITLE
Inconsistency when switching parser modes

### ISSUE THREAD

**Issue by pothos** [nikomatsakis/lalrpop#179]
Using the type `#[recursive_ascent]` the attached examples compiles correctly, but as soon as this switch is gone errors like this occur:

```
   --> src/grammar.rs:426:101
    |
426 |                             Tok::Dot { location: __tok0, value: __tok1 } => __Symbol::Term_22_2e_22(__tok0, __tok1),
    |                                                                                                     ^^^^^^^^^^^^^^
    |
    = note: the following parameter type was expected: (std::string::String, std::string::String)

error[E0061]: this function takes 1 parameter but 2 parameters were supplied
```

Did I overlook somethink or is it a bug in the table driven mode? `#[LALR]` does not impact the behaviour.

https://tubcloud.tu-berlin.de/index.php/s/0TLepTZQDrrLp0W

**Comment by nikomatsakis** [comment]
Interesting. This seems like a bug to me, I'm not sure!

**Comment by pothos** [comment]
splendid, this can be closed now :) Big thanks to @wieczyk – just this evening I wanted to investigate it at the Rust meeting in my neighbourhood and realized that it was fixed already.

Now my grammar.rs is only 16 MB with LALR and needs less memory to compile, 29 MB without LALR, 23 MB LALR+recursive_ascent.
