### ISSUE TITLE
Failure under Windows

### ISSUE THREAD

**Issue by vadz** [nikomatsakis/lalrpop#18]
Just trying to follow the tutorial with the nightly (1.4) build under Windows I get `E0277` warnings at `src/lexer/nfa/mod.rs` lines 293 and 294 and then this at the end:

```
   Compiling lalrpop v0.5.0
failed to run custom build command for `lalrpop v0.5.0`
Process didn't exit successfully: `...\target\debug\build\lalrpop-f7721ad1ac348df2\build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 5, message: "Access is denied." } }', ../src/libcore\result.rs:734
```

I have really no idea what could this be about, would you have any? FWIW `build-script-build.exe` is executable and can be ran without arguments, but I don't know how does Cargo run it (it doesn't show any details even with `-v`).

**Comment by kinghajj** [comment]
For what it's worth, I'm getting the same error with v0.6.1, on both the stable and nightly releases of Rust.

**Comment by nikomatsakis** [comment]
I've nested tested under windows so I'm not too surprised, but I also have no idea what that's about. I'll try to get a VM up to investigate (or perhaps invest some effort in better error messages in the event of O/S failures!)

**Comment by brson** [comment]
[PR for the fix is up](https://github.com/nikomatsakis/lalrpop/pull/20). Windows returns different error codes for missing files.

**Comment by nikomatsakis** [comment]
Is this fixed now?

**Comment by nikomatsakis** [comment]
Actually, based on @brson's comments from #20, I'm going to assume it is and close the issue. Feel free to re-open or open a new issue if there is a new problem. Thanks @brson for the fix.
