### ISSUE TITLE
[lalrpop-intern] provide a way to pick a random string

### ISSUE THREAD

**Issue by aochagavia** [nikomatsakis/lalrpop#181]
First of all, I am not sure what the scope is of `lalrpop-intern`, so feel free to ignore this issue in case it doesn't fit the purposes of the crate.

I am writing a toy text generator based on Markov chains that requires storing lots of strings. This seemed to be a perfect use case for interning, so I am using this library. The only problem so far is that I would like to generate sentences. In order to do this, I need to pick a starting word and feed it to my generator. However, the `Interner` offers no way to pick random strings. There are of course workarounds, but they have their own drawbacks.

Would it make sense to extend the `lalrpop-intern` crate to support this use case? Or would you prefer to keep things as they are right now?

**Comment by Marwes** [comment]
There is an issue open for replacing lalrpop-intern #158 so depending on it seems like a bad idea regardless. Maybe look into https://crates.io/crates/string_cache instead?

**Comment by nikomatsakis** [comment]
@aochagavia yeah, I'd probably not use this crate, which may have that long to live.

**Comment by aochagavia** [comment]
Ok, thanks for the suggestion of using `string_cache`!
