### ISSUE TITLE
Can't have "extern crate cairo;" before my "use" lines

### ISSUE THREAD

**Issue by federicomenaquintero** [nikomatsakis/lalrpop#200]
I wanted to start my grammar with
```
extern crate cairo;
use std::str::FromStr;
use cairo::MatrixTrait;
```
but I'm seeing that lrgrammar.lalrpop doesn't have extern in the Use nonterminal.

For now I put in a bring_in_cairo.rs which just contains "``extern crate cairo;``", and in my .lalrpop file I have
```
use bring_in_cairo::cairo::MatrixTrait;
```
which seems awkward.

Am I using extern crates totally wrong, or is this a missing feature?

**Comment by nikomatsakis** [comment]
Hmm, normally extern crates go at the root of one's project, and I guess I never expected to have the LALRPOP grammar live in the root module. That is, I expect a project layout where you have `parser.lalrpop` or whatever which is a private sub-module, and you re-export the routines that you want. 

That said, I see no reason not to permit `extern crate`, seems like a useful feature.

**Comment by federicomenaquintero** [comment]
No, this is exactly the sort of thing I wanted to hear.  I started sprinkling "extern crate cairo" and "extern crate glib" in various files when I first started learning Rust and converting librsvg to it - but if extern crates should be pulled in in the root (lib.rs, correct?), I can certainly do that.

I don't remember where I got the idea to put "extern crate cairo" in normal source files, not in the root module... serves me right for cutting&pasting a file's header and then trimming it when the compiler warns about unused modules :)
