### ISSUE TITLE
Ability to resolve ambiguities by assigning priorities

### ISSUE THREAD

**Issue by wagenet** [nikomatsakis/lalrpop#202]
I'm not sure if this is the correct solution, but I'd love to be able to resolve ambiguities by giving a priority to one item over another. I have some code that worked correctly until I tried to make some keyword strings case-insensitive with a regex. My understanding from other things I read is that Strings take priority over Regexs. I'd love to just be able to say that I want one Regex to take priority over another in the same way.

I should say that I'm happy to help with this if I can get some direction.

**Comment by nikomatsakis** [comment]
So really all we need is some kind of syntax. The code is written to permit an arbitrary number of priorities. In the past I've gotten hung up on more advanced things, like supporting multiple lexer states, but it seems like we should just try to focus on this one problem -- although another thing i'd really like to solve at the same time is making it easy to skip comments, which I bet you're going to want too. =)

Strawman proposal: Add a "match...else" section that defines the lexer. Only legal if you don't use a separate lexer. Something like this:

```rust
match {
    // highest priority:
    r"[aA][bB][cC]", // case insensitive abc keyword
    r"//.*" => (), // skip comments -- the `=> ()` is the only kind of arm permitted
} else {
    // next priority:
    r"[a-z]+" // all lowercase
} else {
    // next priority:
    _, // all other tokens that appear in the grammar
};
```

Probably this is kind of terrible, but I am thinking a bit forward to the idea that we may eventually want to support other kinds of actions after the `=>` -- the default action would be "forward this token", of course.

If you had such a `match` section, it would be an error if you used a token in your grammar that does not appear in the `match`, unless you have that `_` thing somewhere, which is open-ended.

**Comment by wagenet** [comment]
@nikomatsakis I guess this would mean that I have to figure out how to write a basic lexer, huh?

**Comment by nikomatsakis** [comment]
@wagenet well, that's maybe the faster short-term solution. i'm told you can combine https://github.com/LeoTestard/rustlex with LALRPOP. But I am somewhat motivated to have a better solution here. what LALRPOP has now is really too primitive to be usable.

I was thinking that it might be desirable to let you give different names to the tokens, in addition to specifying their priority:

```rust
match {
    // highest priority:
    r"[aA][bB][cC]" => "ABC",
    r"//.*" => (), // skip comments -- the `=> ()` is the only kind of arm permitted
} else {
    // next priority:
    r"[a-z]+" => ID,
} else {
    // next priority:
    _, // all other tokens that appear in the grammar
};
```

Here the regex, when matched, would produce the terminal on the RHS of the `=>` (i.e., `"ABC"` or `ID`), which could then be used in the grammar itself. This would allow you to avoid repeating the regular expressions in more than one place.

**Comment by nikomatsakis** [comment]
Closing in favor of the existing bug https://github.com/nikomatsakis/lalrpop/issues/195

**Comment by wagenet** [comment]
Related to #10
