### ISSUE TITLE
Enable constructing LR1 states via lane-table algorithm based on an environment variable

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/lalrpop#203]
In order to test the lane-table LR1 state construction -- without enabling it universally -- one easy option might be to have [the `build_lr1_states()` function](https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop/src/lr1/build/mod.rs#L16-L18) check some kind of environment variable (e.g., `LALRPOP_LANE_TABLE`) and -- if it is set -- use the lane-table technique. 

This is basically as simple as changing [the existing `if false { ... }`](https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop/src/lr1/build/mod.rs#L22-L24) to read something like

```rust
    if std::env::var("LALRPOP_LANE_TABLE").is_ok() {
        return build_lane_table_states(grammar, start);
    }
```

except that I think I would also move the code into the `profile!` macro below.

**Comment by nikomatsakis** [comment]
cc @wieczyk

**Comment by nikomatsakis** [comment]
Once the switch is in place, we could then test whether we can run `cargo test` with the flag enabled -- if true, we could add that to the travis configuration.

Eventually of course the plan is to remove the switch and just use lane table for everything.

**Comment by wieczyk** [comment]
I will handle it.

**Comment by nikomatsakis** [comment]
This is done.
