### ISSUE TITLE
Add option to disable implicit whitespace skipping

### ISSUE THREAD

**Issue by JustANull** [nikomatsakis/lalrpop#21]
The ability to disable implicit skipping of whitespace would be useful. Is it possible to add this as an option at the top of the file or somewhere else? I'm trying to parse a language with significant whitespace before tokens which is being automatically trimmed. If disabling that behavior is already possible, I was unable to find out how.

**Comment by nikomatsakis** [comment]
Currently, this is only possible if you use a custom tokenizer, however I do want to add the ability to customize what gets skipped. I'm going to close this as a dup of https://github.com/nikomatsakis/lalrpop/issues/14, which talks about the more general feature. Thanks!
