### ISSUE TITLE
Investigate test results for lane-table-method.

### ISSUE THREAD

**Issue by wieczyk** [nikomatsakis/lalrpop#210]
Unfortunately not all tests are working with current implementation of lane table. 

Find root cause of failing tests and solve problem.

```
$ LALRPOP_LANE_TABLE=enabled cargo test

.
.
.

failures:
    lr1::build::test::expr_grammar1
    lr1::build_lalr::test::figure9_23
 
test result: FAILED. 144 passed; 2 failed; 0 ignored; 0 measured
```

**Comment by nixpulvis** [comment]
FWIW these tests are failing inside the `lalrpop` directory. If you're new to `cargo` first make sure you are in that location.
