### ISSUE TITLE
Small typo on section 4 of the tutorial

### ISSUE THREAD

**Issue by JonathanGallagher** [nikomatsakis/lalrpop#219]
pub Expr: Box<Expr> = { // (1)
    Expr ExprOp Factor => Box::new(Expr::Op(<>)) // (2)
    Factor,
};

Omitted a comma which leads to code that doesn't compile.  Should be

pub Expr: Box<Expr> = { // (1)
    Expr ExprOp Factor => Box::new(Expr::Op(<>)), // (2)
    Factor,
};

Otherwise, it's a fantastic tutorial!!

**Comment by nikomatsakis** [comment]
Ah, thanks =) Any chance you want to open a PR to fix it?

**Comment by JonathanGallagher** [comment]
No problem.  I've actually never done a pull request before, but I'll do it
soon.
