### ISSUE TITLE
Trouble with creating a basic vector of structs

### ISSUE THREAD

**Issue by gjtorikian** [nikomatsakis/lalrpop#241]
Hello! I'm pretty familiar with Bison/Flex parsing and lexing, but for a new hobby project I wanted to try my hand at implementing the grammar in Rust, which I am not too familiar with. 

I was wondering if you'd be able to help me out: I want to create a very basic vector of objects. For example, given a text file like:

```
red car {
  slow
}
blue boat {
  fast
}
green plane {
  fast 
}
```

I wanted to be able to parse it and create a `Vec<Vehicle>`. I started with an _ast.rs_ that looks like this:

``` rust
pub struct Vehicle {
    color: String,
    name: String,
    speed: Speeds
}

pub enum Speeds {
    FastSpeed,
    SlowSpeed
}
```

But I'm having trouble writing the `lalrpop` itself:

``` rust
pub file: Vec<Vehicle> =
  <Vehicle*>;

Vehicle: Vehicle = {
  <Color> <Name> "{" <SpeedType> "}"
};

SpeedType: Speeds = {
  "fast" => Speeds::FastSpeed,
  "slow" => Speeds::SlowSpeed,
};

Color: String = r"[a-zA-Z0-9]+" => <>.to_string();
Name: String = r"[a-zA-Z0-9]+" => <>.to_string();
```

I want the output of `parse_file` to be a vector comprised of `Vehicle`s, so that I can iterate over them and do other stuff. But I'm not quite grasping how to "populate" the struct. I feel like `pub file: Vec<Vehicle> = <Vehicle*>;` is all wrong; the rest of the file would seem like regular grammar definitions.

Would you be able to provide any assistance here? 🙏

**Comment by da-x** [comment]
It looks that `larlpop` can populate the `Vector` for you, and you can simply return it from the production rule:

```rust
pub file: Vec<Vehicle> = 
    <Vehicle*> => <>;
```

From a performance perspective in the generated code, move semantics apply yo the `Vector`, and it will grow mutably via `push`:

```rust
#[allow(unused_variables)]
fn __action10<
    'input,
>(
    input: &'input str,
    (_, v, _): (usize, ::std::vec::Vec<Vehicle>, usize),
    (_, e, _): (usize, Vehicle, usize),
) -> ::std::vec::Vec<Vehicle>
{
    { let mut v = v; v.push(e); v }
}
```
So it seems all okay to me :)

**Comment by gjtorikian** [comment]
Well, the error I receive is

```
expected struct `ast::Vehicle`, found tuple
```

So I'm still fundamentally misunderstanding how to implement this. 😞

**Comment by da-x** [comment]
This works for me (assuming `Vehicle` and `Speeds` are defined as above in another module `ast`).

```rust
use ast::{Vehicle, Speeds};

grammar;

pub file: Vec<Vehicle> = <Vehicle*> => <>;

Vehicle: Vehicle = {
  <c:Color> <n:Name> "{" <s:SpeedType> "}" => {
    Vehicle { color: c, name : n, speed: s }
  }
};

SpeedType: Speeds = {
  "fast" => Speeds::FastSpeed,
  "slow" => Speeds::SlowSpeed,
};

Color: String = r"[a-zA-Z0-9]+" => <>.to_string();
Name: String = r"[a-zA-Z0-9]+" => <>.to_string();
```

**Comment by gjtorikian** [comment]
@da-x Thank you so much! I should've pasted some updated code--I had the `=> { ... }` action sequence started, but I was misunderstanding the `<c:` / `<n:` "aliasing" (I'm reading https://github.com/nikomatsakis/lalrpop/blob/92055a1e2c3f1cfa58c3dbaef68c0e0ec48214b1/doc/tutorial.md and not sure what this action is called). 

Totally working now. Thanks!
