### ISSUE TITLE
Terminal ambiguity with string/regexp precedence 

### ISSUE THREAD

**Issue by gjtorikian** [nikomatsakis/lalrpop#248]
Suppose there is a grammar like this:

```
pub Term: String = {
    "type" <f:Field> => f
};

Field: String = {
  <n:Name> => n
};

Name: String = r"[_A-Za-z][_0-9A-Za-z]*" => <>.to_owned();
```

The idea is to parse some text file of keywords and identifiers. `type` is a keyword, and anything after it is a field identifier. So:

```
type _foo
type wow
type A_123_wow
```

are all valid.

However, so is this:

```
type type
```

The significance of the term after `type` is irrelevant, so long as it matches the `Name` regex.

However, attempting to use this grammar to parse a file throws an `UnrecognizedToken` on the identifier. I'm not sure why, but my guess is that, since fixed string lengths have higher precedence over regular expressions, it's interfering somehow? I tried using a `match` clause to separate the precedence between `r"[_A-Za-z][_0-9A-Za-z]*"` and `_` but that didn't fix it. Is there a workaround to this?

**Comment by sgodwincs** [comment]
I'm assuming that the builtin lexer is treating any whitespace separated `type` as a separate token from the regex name. This could definitely be solved by writing your own lexer, but maybe there is someway to tell lalrpop to handle this differently. Though, if this is the extent of your grammar, writing a lexer would be fairly trivial.

Maybe @nikomatsakis has a better solution for this.

**Comment by nikomatsakis** [comment]
Indeed, the built-in lexer will treat `type` as a keyword and -- hence -- a distinct token. Currently, by default, regular expressions get more precedence. I usually solve this by adding keywords into the "identifier" section, like so:

```
pub Term: String = {
    "type" <f:Field> => f
};

Field: String = {
  <n:Name> => n
};

Name: String = {
    r"[_A-Za-z][_0-9A-Za-z]*" => <>.to_owned(),
    "type" => "type".to_owned(),
};
```

However, it might be interesting to try and have some way to do this automatically. I'm not sure how that would work off-hand -- I guess we would have to do a "preprocessing" step in which we take a single terminal (e.g., the regex) and expand it to multiple options.

**Comment by gjtorikian** [comment]
Thank you! This workaround is just fine for me now.
