### ISSUE TITLE
Parens in strings in actions causes parse errors

### ISSUE THREAD

**Issue by dagit** [nikomatsakis/lalrpop#25]
If you define a rule like this:

```
thing = {
  "a" => "("
};
```

You'll get a parse error at semicolon like this:
```
--- stdout
src/huh.lalrpop:5:2: 5:2 error: unexpected token: `;`
  };
   ^
```

**Comment by nikomatsakis** [comment]
Evidently the code I have that tries to balance parens in arbitrary rust code doesn't take string literals into account. I'll take a look. :)

**Comment by nikomatsakis** [comment]
OK, sorry I let this bug sit so long. Seems like it could be annoying. I ought to have a fix soon but I wanted to mention that there is an easy workaround, I expect, of adding `/* ) */` into your code to balance out the parentheses.
