### ISSUE TITLE
Extra tokens do not produce a parse error

### ISSUE THREAD

**Issue by tso** [nikomatsakis/lalrpop#253]
Not sure if this is bug or feature request. The grammar defined by:
```rust
use std::str::FromStr;

grammar;

pub Term: i32 = {
    <n:Num> => n,
    "(" <t:Term> ")" => t,
};

Num: i32 = <s:r"[0-9]+"> => i32::from_str(s).unwrap();
```

does not current produce a parse error on `parse_Term("(22))")`.

**Comment by olivren** [comment]
I have the same problem. If any of the rules match the remaining of my parsed string, then the parsing succeeds.

```
grammar;
pub LetterA: i32 = {
    "a" => 1,
};
```

For this grammar, `parse_LetterA("ab")` returns `Err(InvalidToken { location: 1 })`, which is expected.

```
grammar;

pub LetterA: i32 = {
    "a" => 1,
};

pub LetterB: i32 = {
    "b" => 2,
};
```

But for this one, `parse_LetterA("ab")` returns `Ok(1)`.

**Comment by nikomatsakis** [comment]
Hmm. I wonder if this is related to the new parsing table generation algorithm I put in a while back. I suspect so. Thanks for the bug report, I will investigate!

**Comment by nikomatsakis** [comment]
Hmm, no, it *seems* to be a difference between LALRPOP's two internal modes. The parsing table mode (the default) doesn't error out with extra tokens, which is odd.
