### ISSUE TITLE
incorrect lexer ambiguity between identifiers and string literals

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/lalrpop#27]
According to @dagit, LALRPOP reports a lexer ambiguity for a grammar like:

```
use syntax::*;

grammar;

pub VAR = {
  r"[A-Z][_a-zA-Z0-9]*"
};

STRING = {
  r#"""# <r#"[^"]*"#> r#"""#
};
```

which produces output:

```
src/a.lalrpop:10:11: 10:20 error: ambiguity detected between the terminal `r#"[^\"]*"#` and the terminal `r#"[A-Z][_a-zA-Z0-9]*"#`
    r#"""# <r#"[^"]*"#> r#"""#
            ~~~~~~~~~~
```

This seems to be incorrect.

**Comment by nikomatsakis** [comment]
Ah, I was reading the example incorrectly. I think indeed the algorithm is correct, there is an ambiguity here. The problem is that the three regular expressions 

```
r#"""# <r#"[^"]*"#> r#"""#
```

ought to be just one regular expression:

```
r#""[^"]*"#
```

The problem is that you are creating three independent terminals here, and one of them is "any sequence of non-quote characters", which is going to overlap with most any other terminal.

What may be a bit confusing is that even though LALRPOP encourages you to write your terminal regular expressions inline with your grammar, there is still a distinct tokenization and parser phase. That is, the first thing that LALRPOP does is to "tokenize" the input by deciding which string literal or regular expression each item belongs to, without considering where in the grammar those tokens appear. In this case, it would not be able to decide between "contents of string literal" and "identifier". (I'm sort of interested in a hybrid LR(1) model where the tokenizer and parser are more integrated, but anyway.)

**Comment by nikomatsakis** [comment]
Oh, one thing -- if you just want to extract the string without the quotes, you can do:

```
<s:r#""[^"]*""#> => &s[1..s.len()-1],
```

**Comment by dagit** [comment]
Thanks for the example code, that was my next question!

**Comment by pnkfelix** [comment]
> Indeed, I just ran into this as well, and it seems like an excellent thing to add to the docs, maybe with an example of "the right way" (or at least "an idiomatic way") to do typical string literal parsing in LALRPOP.
> 
> (I guess what Niko wrote in their comment _is_ the idiomatic way? Maybe I'll try to make a PR for the docs illustrating it.)

Filed as https://github.com/lalrpop/lalrpop/pull/654
