### ISSUE TITLE
Regex compilation kills performance if parser is called thousands of times

### ISSUE THREAD

**Issue by federicomenaquintero** [nikomatsakis/lalrpop#273]
For librsvg I'm using a lalrpop parser for SVG transforms: https://github.com/GNOME/librsvg/blob/f49facaa0aae457489a4538684a6a4fcd201f921/rust/src/parse_transform.lalrpop

The parser may be called thousands of times for SVGs with many transformations.  Unfortunately, on each call, the parser recompiles its regexes.  This is very slow :)

It would be nice to be able to say, "compile them once and keep them around; I don't care about freeing them", or to have a parser context object or something that would allow freeing the compiled regexes in the end.

**Comment by ehiggs** [comment]
#269 is probably the same issue.

**Comment by nikomatsakis** [comment]
Hmm yes. I have to think about this. Closing in favor of #269.
