### ISSUE TITLE
Being more generic over input?

### ISSUE THREAD

**Issue by LukasKalbertodt** [nikomatsakis/lalrpop#28]
I wondered if it would be possible to accept several types as input. Right now, as I understand it, only `&str` is a valid input. Suppose someone already wrote a lexer and now has a token stream. Or someone actually has a non string "thing" that needs to be parsed somehow. Or, god forbid, someone parsing a non-UTF8 string (`&[u8]`).

In my case: I already wrote a Java 8 lexer and wondered if I could use a/this parser generator on top of my lexer.

So are there any plans to parse something else than a `&str`?

**A bit offtopic**:

Java 8 has global unicode escapes: You can write \uXXXX anywhere in your source file and the corresponding unicode char is substituted for the escape sequence. I wonder if this would be easily implementable with this parser generator. Of course one could preprocess the source string before passing it to lalrpop, but that is not particularly nice.

**Comment by nikomatsakis** [comment]
In fact, there is already support for external lexers, though it is not documented in the tutorial. This test explains shows it is done: 

https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop-test/src/expr.lalrpop

The basic idea is that you define a "extern enum" as shown [in these lines](https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop-test/src/expr.lalrpop#L6-L14):

```
enum Type {
    TokenName => Pattern,
```

where `Type` is the enum type of your tokens, `TokenName` is the name by which you will refer to this token in your grammar, and `Pattern` is the pattern to match. The value of each token will be the enum itself, unless you define binders in your pattern. See e.g. the token `Num` in the example to see how to define a binder (in that case, it extracts a `i32` value and uses it as the value of the token.

I'm going to close this issue, but let me know if you have any more questions.

**Comment by LukasKalbertodt** [comment]
Wow, that was quick, thanks!

I guess I will actually try lalrpop for my java parser then. This project looks promising and I really like the close-to-rust syntax! :)

I'd like to work on this project, but I'm afraid I'm lacking time and (far more important) knowledge to do so. Maybe somewhen in the future...

**Comment by nikomatsakis** [comment]
Great, let me know how you make out.
