### ISSUE TITLE
use regex-syntax?

### ISSUE THREAD

**Issue by BurntSushi** [nikomatsakis/lalrpop#29]
Neat project! I'm not sure if you knew this or not, but in the last few months, the `regex` crate grew a sub-crate called `regex-syntax` which exposes a full blown, well tested, regex parser/AST tree: https://doc.rust-lang.org/regex/regex_syntax/index.html

I briefly looked over yours, and it looks like it supports everything except negative matches. Not sure if that's a deal breaker, but thought I drop a note anyway!

**Comment by nikomatsakis** [comment]
That does look like it would be helpful. The current parser is just a
toy really.


On Fri, Sep 25, 2015, at 10:32 PM, Andrew Gallant wrote:
> Neat project! I'm not sure if you knew this or not, but in the last
> few months, the regex crate grew a sub-crate called regex-syntax which
> exposes a full blown, well tested, regex parser/AST tree:
> https://doc.rust-lang.org/regex/regex_syntax/index.html


> I briefly looked over yours, and it looks like it supports everything
> except negative matches. Not sure if that's a deal breaker, but
> thought I drop a note anyway!


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/nikomatsakis/lalrpop/issues/29

**Comment by nikomatsakis** [comment]
@BurntSushi I forget why I added negative matches; I needed them, I think, just to model some of the more complex cases of character classes, and I added a syntax so that I could unit test them. Or something like that. Anyway I will definitely investigate switching over to the `regex-syntax` crate, which seems to have a similar model to the one I wanted (e.g., break down `[foo]` into disjoint tests over characters).

**Comment by BurntSushi** [comment]
Yeah, much pain was involved in getting character classes to be non-overlapping disjoint sets of ranges. (Negation and Unicode case insensitivity kind of throw a wrench in it.) But it is a very useful property!

**Comment by nikomatsakis** [comment]
I started doing this. It seems like it needs some mild refactoring to deal with character classes gracefully, but I think it's not too hard.

**Comment by BurntSushi** [comment]
@nikomatsakis Great! Let me know if I can help!
