### ISSUE TITLE
Support for generic type parameters

### ISSUE THREAD

**Issue by ihrwein** [nikomatsakis/lalrpop#34]
Hi,

First of all, thanks for this great library :)

I'd like to instantiate different implementations of objects with the same grammar. This is like an abstract factory where the grammar uses the factory to create the objects.

If I could define a generic type parameter with a bound on a parser then I could use the factory.

What do you think about this use-case?

Sou I'd like to add arbitrary `F: Factory` like bounds to every `parse_*` functions.

**Comment by nikomatsakis** [comment]
This is already supported, in fact. You do it by adding the type parameters to the `grammar` declaration, like so:

```rust
grammar<F:Factory>;
```

**Comment by nikomatsakis** [comment]
Ah, actually, I think bounds have to be written as where clauses:

```rust
grammar<F> where F: Factory;
```

Anyway, let me know how that works for you. I don't know that I've tested this functionality very thoroughly, as I myself have not yet had a user for it.

**Comment by ihrwein** [comment]
I began to port my grammar from `rust-peg` to Lalrpop. So far I hit one problem:

```Rust
    pub fn parse_Term<
        F,
        'input,
    >(
        input: &'input str,
    ) -> Result<i32, __ParseError<usize,(usize, &'input str),()>> where
      F: ParserFactory,
    {...}
```

The `'input` lifetime comes after the `F` type parameter.

**Comment by nikomatsakis** [comment]
OK, I think I fixed that problem, thanks for the report!

**Comment by nikomatsakis** [comment]
(You'll have to use the git version for now though.)

**Comment by nikomatsakis** [comment]
Note the new test case:

https://github.com/nikomatsakis/lalrpop/blob/ae027da57edd1b52ebd935e1af0011b5c683ecea/lalrpop-test/src/expr_generic.lalrpop

**Comment by ihrwein** [comment]
Thanks!
