### ISSUE TITLE
Disambiguating post-incrementation/decrementation with addition/subtraction

### ISSUE THREAD

**Issue by saghm** [nikomatsakis/lalrpop#37]
(Sorry if this isn't the right place for this question; this just seemed like the easiest way to get help on this)

I'm attemping to write a parser for JavaScript using lalrpop, and I'm struggling to disambiguate post-incrementation/decremtnation operands (`++`, `--`) from regular addition and subtraction (`+`, `-`).  Currently, the parser file looks like this:

```
// Statement nonterminal
pub Stmt: Stmt = {
    <Var> "=" <Exp>  ";" => Stmt::Assign(<>),
    "var" <Var> "=" <Exp> ";" => Stmt::Decl(<>),
};

// Expression nonterminal
pub Exp: Exp = {
    <e:Exp> <o:AddOp> <m:MulExp> => Exp::BinExp(Box::new(e), o, Box::new(m)),
    MulExp,
};

AddOp: BinOp = {
    "+" => BinOp::Plus,
    "-" => BinOp::Minus,
};

// Parses multiplication
MulExp: Exp = {
    <m:MulExp> <o:MulOp> <t:Term> => Exp::BinExp(Box::new(m), o, Box::new(t)),
    Term,
};

MulOp: BinOp = {
    "*" => BinOp::Star,
    "/" => BinOp::Slash,
};

// Parses numbers and parenthetical expressions, and variables
Term: Exp = {
    Float => Exp::Float(<>),
    Var => Exp::Var(<>),
    "(" <Exp> ")",
};

Float: f64 = {
    r"-?[0-9]+(\.[0-9]+)?" => f64::from_str(<>).unwrap()
};

Var: String = {
    r"[A-Za-z_][0-9A-Za-z_]*" => String::from(<>)
};
```

And the AST looks like this (excluding method/trait implementations I've defined for the structs):

```
pub enum BinOp {
    Minus,
    Plus,
    Slash,
    Star,
}

pub enum Exp {
    BinExp(Box<Exp>, BinOp, Box<Exp>),
    Float(f64),
    Var(String),
    PostDec(Box<Exp>),
    PostInc(Box<Exp>),
    PreDec(Box<Exp>),
    PreInc(Box<Exp>),
}

pub enum Stmt {
    Assign(String, Exp),
    Decl(String, Exp),
}
```

(Sorry, I know that's quite a bit to look at!)

My issue is that if I add the ability to parse post-incrementation operations, e.g. `x++`, then I get a shift-reduce conflict because the parser can't disambiguate whether to shift the first `+` or to reduce and start parsing an addition expression (and similarly for post-decrementation and subtraction).

I was wondering if there is any functionality in lalrpop at this time to be able to disambiguate between these two cases. I admit that my knowledge of parsing is not extremely advanced, so I may be missing some obvious way to deal with these cases. Any tips/suggestions would be greatly appreciated.

Thanks!

**Comment by nikomatsakis** [comment]
Can you give the example where you added the `++`?

**Comment by saghm** [comment]
I tried a couple of places. One was to change `Term` to this:

```
Term: Exp = {
    Float => Exp::Float(<>),
    Var => Exp::Var(<>),
    "(" <Exp> ")",
    <Term> "++" => Exp::PostInc(Box::new(<>)),
};
```

But this didn't work because after reading a `Term` and a single `+`, it could either be parsing an add operation or a incrementation.

The other way I tried tried involved making a separate nonterminal for incrementation/decrementation expressions and a nonterminal for `++` and `--`, but this just turned the shift/reduce conflict into a reduce/reduce, so it didn't solve anything.

**Comment by saghm** [comment]
I got it working with the following changes (to the original):

```
MulExp: Exp = {
    <m:MulExp> <o:MulOp> <t:Term> => Exp::BinExp(Box::new(m), o, Box::new(t)),
    PreExp,
};

PreExp: Exp = {
    "++" <PostExp> => Exp::PreInc(Box::new(<>)),
    PostExp,
};

PostExp: Exp = {
    <Term> "++" => Exp::PostInc(Box::new(<>)),
    Term,
};
```

I'm not sure why I didn't see it like this in the first place, but it seems pretty obvious to me now!

Sorry to bother you about this!

**Comment by nikomatsakis** [comment]
No problem, glad you got it working!


Niko

<div>-------- Original message --------</div><div>From: Saghm Rossi <notifications@github.com> </div><div>Date:10/30/2015  13:08  (GMT-05:00) </div><div>To: nikomatsakis/lalrpop <lalrpop@noreply.github.com> </div><div>Cc: Niko Matsakis <niko@alum.mit.edu> </div><div>Subject: Re: [lalrpop] Disambiguating post-incrementation/decrementation with
  addition/subtraction (#37) </div><div>
</div>I got it working with the following changes (to the original):

MulExp: Exp = {
    <m:MulExp> <o:MulOp> <t:Term> => Exp::BinExp(Box::new(m), o, Box::new(t)),
    PreExp,
};

PreExp: Exp = {
    "++" <PostExp> => Exp::PreInc(Box::new(<>)),
    PostExp,
};

PostExp: Exp = {
    <Term> "++" => Exp::PostInc(Box::new(<>)),
    Term,
};
I'm not sure why I didn't see it like this in the first place, but it seems pretty obvious to me now!

Sorry to bother you about this!
