### ISSUE TITLE
Building LALRPOP fails on latest nightly

### ISSUE THREAD

**Issue by mAarnos** [nikomatsakis/lalrpop#43]
If I try to build LALRPOP on the latest nightly, the build fails rather spectacularly by first spewing out a couple thousand warnings and then hitting an internal compiler error. Changing the machine and/or the  OS doesn't affect the result. Also, both 0.7.0 and the current master branch fail in exactly the same way. Here is a log of the failing build:

[failing_build.txt](https://github.com/nikomatsakis/lalrpop/files/47513/failing_build.txt)

**Comment by nikomatsakis** [comment]
Heh, yes. I'll patch that. Thanks!
