### ISSUE TITLE
Cannot appear to match against newlines

### ISSUE THREAD

**Issue by duane** [nikomatsakis/lalrpop#49]
For the given grammar:

```rust
use std::str::FromStr;

grammar;

pub Id: String = <s:r"[_a-zA-Z][_a-zA-Z0-9]*"> => String::from(s);
pub Expr: Vec<String> = {
  <i:(Id ",")*> <u:Id?> => {
    let mut total_vec: Vec<String> = i.into_iter().map(|t|{t.0}).collect();
    if u.is_some() {
      total_vec.push(u.unwrap());
    }
    total_vec
  }
};

pub Name: String = {
  "HEADER(" <s:Id> ")" => s
};

pub SEMI_SEP = r";+";
pub NEWLINE_SEP = r"\n+"; // will only compile with `"\n+"; regex doesn't work here.

File<Sep>: (String, Vec<Vec<String>>) = {
  <name:Name> <lines:(Sep Expr)*> => (name, lines.into_iter().map(|t|{t.1}).collect::<Vec<Vec<String>>>())
};

pub NewlineFile = File<NEWLINE_SEP>; // WILL NOT COMPILE
pub SemiFile = File<SEMI_SEP>;
```

and the following test:

```rs
pub mod test;

#[test]
fn semi_test() {
  let (name, ids) = test::parse_SemiFile(r#"HEADER(this_is_the_name);id1,id2;id3;id4,id5;;id6"#).unwrap();
  assert_eq!(String::from("this_is_the_name"), name);
  assert_eq!(4, ids.len());
}

#[test]
fn newline_test() {
  let (name, ids) = test::parse_NewlineFile(r#"HEADER(this_is_the_name)
id1,id2
id3
id4,id5

id6"#).unwrap();
  assert_eq!(String::from("this_is_the_name"), name);
  assert_eq!(4, ids.len());
}

fn main() {}
```

`semi_test` works flawlessly; `newline_test` fails. If using the raw string (i.e. the regular expression instead of the newline literal) it doesn't even compile, and if using the normal string, it simply fails.

So—am I misunderstanding something here, or is newline special cased to not work where the semicolon would work?

**Comment by joelself** [comment]
I'm not sure if this is related, but I can't match newlines, spaces or tabs without explicitly using ```\\n \\r \\ \\t```.  I have:

```rust
pub Space: Space = {
    "\ " => Space::SPACE,
    "\t" => Space::TAB,
};

pub NewLine: NewLine = {
    "\r\n" => NewLine::SLASHRSLASHN,
    "\r" => NewLine::SLASHR,
    "\n" => NewLine::SLASHN,
};
```

Then to test it I need:

```rust
print!("{:?}\n", toml::parse_Ignore("\\ \\n\\t"));
```

which works, but the text I want to parse isn't going to have ```\\``` in front of every newline, space and tab. Is there a way to get lalrpop to parse these characters?

**Comment by nikomatsakis** [comment]
Currently we implicitly skip whitespace when you use the builtin tokenizer.

**Comment by nikomatsakis** [comment]
I'm going to close this issue as a dup of https://github.com/nikomatsakis/lalrpop/issues/14 -- right now, we *always* skip whitespace, but there is a need to make this configurable, both so you can skip more (e.g. comments) and less (as here). Thanks for the report, however.

In the meantime, using a custom lexer is the primary workaround, though I suppose one could preprocess the input string to replace `\n` with some other token.

**Comment by flouthoc** [comment]
> I'm going to close this issue as a dup of https://github.com/nikomatsakis/lalrpop/issues/14

Correct link is https://github.com/lalrpop/lalrpop/issues/14
