### ISSUE TITLE
Build failure on Windows

### ISSUE THREAD

**Issue by mAarnos** [nikomatsakis/lalrpop#53]
If I try to use the version 0.8.0 of LALRPOP I get the following build failure on both a Windows 7 and a Windows 10 machine. The Rust version was 1.5 stable. I ran into #41 which isn't fixed in 0.7.0 so I am kinda blocked by this issue. 

    Compiling lalrpop v0.8.0
    failed to run custom build command for `lalrpop v0.8.0`
    Process didn't exit successfully: `C:\Users\Mikko\Desktop\lalrpop_test\target\debug\build\lalrpop29dda9a615e8fbeb\build-script-build` (exit code: 101)
    --- stderr
    thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error
    { repr: Os { code: 5, message: "Access is denied." } }', ../src/libcore\result.rs:738

All the other parts of LALRPOP, i.e. lalrpop-util, lalrpop-snap and lalrpop-intern compile just fine.

**Comment by nikomatsakis** [comment]
Hmm. I need to setup a Windows box of my own! It sounds like this might have to do with the fact that LALRPOP tries to make its intermediate `.rs` files read-only?

**Comment by mAarnos** [comment]
I noticed that if I set up my TOML file like so

    [dependencies.lalrpop-util]
    git = "https://github.com/nikomatsakis/lalrpop.git"

    [build-dependencies.lalrpop]
    git = "https://github.com/nikomatsakis/lalrpop.git"

instead of 

    [dependencies.lalrpop-util]
    version = "0.8.0"

    [build-dependencies.lalrpop]
    version = "0.8.0"

then everything works fine. So it seems that the bug has already been fixed in some commit between the version in crates.io and the latest version, or there is something pretty interesting going on. I tried going through some of the commits but didn't find anything suspicious at a quick glance.

**Comment by nikomatsakis** [comment]
Huh. Well, I was going to issue a new release soon anyway -- so maybe it is fixed. However, it may also just be that this triggers some sort of make clean? Unclear.

**Comment by oconnor0** [comment]
I have encountered this same error - where the .rs generated from the .lalrpop is marked read-only and so gets that "Access is denied." error - on Windows 10, Rust 1.6, and LALRPOP 0.9.0.

**Comment by oconnor0** [comment]
For what it's worth, commenting out line 105 (https://github.com/nikomatsakis/lalrpop/blob/e3b2f31e8e9f9061df1fe169a61b590502496a3f/lalrpop/src/build/mod.rs#L105) in `make_read_only` appears to fix the problem for me. I'm not sure what the "correct" solution on Windows is.

**Comment by nikomatsakis** [comment]
Can somebody run with RUST_BACKTRACE=1 and let me know what you see? I am going to try and setup a windows laptop locally to reproduce as well.

**Comment by oconnor0** [comment]
When I run `cargo build` with `RUST_BACKTRACE=1` in the environment, I get:

```
   Compiling core v0.0.1 (file:///E:/Source/system-zero/core)
failed to run custom build command for `core v0.0.1 (file:///E:/Source/system-zero/core)`
Process didn't exit successfully: `E:\Source\system-zero\core\target\debug\build\core-23200fa3d5d39d6c\build-script-build` (exit code: 101)
--- stderr
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 5, message: "Access is denied." } }', ../src/libcore\result.rs:741
stack backtrace:
   0:           0x8a08ec - <unknown>
   1:           0x8a8b8e - <unknown>
   2:           0x86a1fc - <unknown>
   3:           0x86a96b - <unknown>
   4:           0x89cf62 - <unknown>
   5:           0x8bd678 - <unknown>
   6:           0x40167c - <unknown>
   7:           0x401512 - <unknown>
   8:           0x8a8628 - <unknown>
   9:           0x8936b1 - <unknown>
  10:           0x8a852d - <unknown>
  11:           0x40196a - <unknown>
  12:           0x4013b4 - <unknown>
  13:           0x4014e7 - <unknown>
  14:     0x7fff56f18101 - <unknown>
```

**Comment by nikomatsakis** [comment]
This may now be fixed by #66 -- perhaps others want to give it a try?

**Comment by mAarnos** [comment]
Works, but so does just 0.9.0.

**Comment by nikomatsakis** [comment]
Closing as fixed.
