### ISSUE TITLE
unrecognized annotation `inline`

### ISSUE THREAD

**Issue by LukasKalbertodt** [nikomatsakis/lalrpop#54]
With this simple grammar:
```rust
grammar;

#[inline]
Foo = { "a", "b" };
```

I get:
```
src/grammar/test.lalrpop:3:3: 3:8 error: unrecognized annotation `inline`
  #[inline]
    ~~~~~~
```

I suppose this isn't correct, is it? I read a bit through the lalrpop-source files and it seems that this error really shouldn't happen. The output is in `normalize/prevalidation.rs:83`. Maybe something is wrong with the string interner?

**Comment by nikomatsakis** [comment]
Definitely seems wrong.

**Comment by LukasKalbertodt** [comment]
I'm very sorry: I tested it with version `0.7`. In `0.8` the error does not occur. My bad!

**Comment by nikomatsakis** [comment]
I also could not reproduce. :)
