### ISSUE TITLE
Partial generated .rs file prevents rebuild

### ISSUE THREAD

**Issue by LukasKalbertodt** [nikomatsakis/lalrpop#57]
I have a `.lalrpop` file in my project that results in an shift-reduce-conflict. When building, lalrpop partially generates the `.rs` file which looks like this:

```rust
#![allow(unused_imports)]
#![allow(unused_variables)]
// here are my imports from the lalrpop file
extern crate lalrpop_util as __lalrpop_util;
use self::__lalrpop_util::ParseError as __ParseError;
```

This file then prevents lalrpop from rebuilding the `lalrpop` file if it wasn't modified. When just executing `cargo build` again, `rustc` says that the function `parse_GoalSymbol` does not exist. It's even worse when you are just testing, if some lalrpop file is valid (without using the `pub` symbols in your rust code). Then the second `cargo build` works without failure, which is super confusing.

I think the best solution is to not write anything to the `.rs` file until everything was processed correctly.

**Comment by nikomatsakis** [comment]
Hmm, yes, that sounds really annoying! :) 

> I think the best solution is to not write anything to the .rs file until everything was processed correctly.

Agreed. Or else remove the `.rs` I'm surprised I did otherwise.
