### ISSUE TITLE
Option to pass arguments through the parser

### ISSUE THREAD

**Issue by TyOverby** [nikomatsakis/lalrpop#62]
I'd like to create an AST, but instead of `Box`ing branches, I'd like to use an arena for the allocations.

Instead of 

```rust
pub enum Expr {
    Number(i32),
    Op(Box<Expr>, Opcode, Box<Expr>),
}
```

I'd like 

```rust
pub enum Expr<'a> {
    Number(i32),
    Op(Box<&'a Expr<'a>>, Opcode, Box<&'a Expr<'a>>),
}
```

However, this requires plumbing an arena all the way through the parser.  Is this possible yet?

**Comment by TyOverby** [comment]
Looks like this is already possible!  In fact, your expr_arena example is *exactly* what I wanted!  You already have a TODO for documenting that functionality, so I'll close this issue!

**Comment by nikomatsakis** [comment]
Sorry, I missed this issue somehow :( but glad you found it!
