### ISSUE TITLE
Ignore Whitespace

### ISSUE THREAD

**Issue by Binero** [nikomatsakis/lalrpop#68]
I want to use this library to parse the OpenDDL language, which is interesting in that whitespace is irrelevant at any position. As such, is there a way to tell the library to ignore certain characters? 

Also, there is a small exception to this. In a string, whitespace *is* relevant. So I would like to ignore whitespace in all places but one.

**Comment by nikomatsakis** [comment]
Right now, you'd have to write your own lexer I think. Customizing how
the built-in lexer handles whitespace is a high priority though.

**Comment by nikomatsakis** [comment]
This is sort of a dup of #10. Going to close in favor of that.
