### ISSUE TITLE
Allow nonterminals to carry additional type parameters

### ISSUE THREAD

**Issue by Binero** [nikomatsakis/lalrpop#72]
Is there a way to do this? 

``` rust
pub LiteralDecimal<Out>: Out = <int:r"()[0-9]\_?)*[0-9]"> => int.parse<Out>();
```

**Comment by nikomatsakis** [comment]
Hmm. There is not, but it seems like it could indeed be useful.

I think you could do this by making a dummy nonterminal whose type was the type you wanted though, like

```
pub i32: i32 = () => ();
```

and then `LiteralDecimal<i32>`

**Comment by nikomatsakis** [comment]
@Binero by the way, in case it wasn't clear, it **is** possible to put type parameters **on the grammar** (which then apply to all nonterminals). See e.g. [this sample test](https://github.com/nikomatsakis/lalrpop/blob/master/lalrpop-test/src/expr_generic.lalrpop)

**Comment by nikomatsakis** [comment]
The syntax proposed here is actually already used by macros. I..think i'm going to close this issue, even though there may be a use-case here. It's not something I've seen repeated, and I think that type-parameters at the grammar level feel sufficient for now.
