### ISSUE TITLE
Use `IntoIterator<Item = char>` instead of &str and do not require ending in EOF

### ISSUE THREAD

**Issue by Binero** [nikomatsakis/lalrpop#73]
As the parser generated only need 1 lookahead, it should be able to use an iterator instead of a string, and not require it to end in EOF. (i.o.w. allow infinite data)

This has the benefit that when reading from for example a socket, you do not have to wait till all data has arrived before you can start parsing. 

Specifically for an issue I am having, I want to use lalrpop in two stages, a tokenizer and a parser. It'd allow for reading tokens without it either reading all tokens at once, either never matching because it doesn't find EOF.

**Comment by nikomatsakis** [comment]
The *parser* uses only one token of lookahead, but the *lexer* can use arbitrary lookahead. It seems like you may want to write your own tokenizer (or use something like [rustlex](https://github.com/LeoTestard/rustlex)).

**Comment by nikomatsakis** [comment]
Also, I think there is a mode for invoking the parser that does not require EOF -- but I have to check if we make it public. I know I wanted to at some point.

**Comment by nikomatsakis** [comment]
OK, thinking on this a bit more -- it's probably not too hard to rejigger the generated lexer to buffer up the characters that it doesn't use.

**Comment by Binero** [comment]
The lexer can use arbirtrary lookahead, which is still possible in an iterator, right? The advantage of using an iterator over chars is that you don't have to have a complete data-set.

**Comment by nikomatsakis** [comment]
@Binero right, it could be ported to use an iterator: that's what I meant by we can buffer characters. I have to look at how easy it would be, I forget how I generate the code, probably not too hard.

**Comment by Binero** [comment]
Out of interest, why would it require a buffer for the characters?

**Comment by nikomatsakis** [comment]
@Binero imagine one regular expression like `'[a-z]+'` and one like `'[a-z]+` (Rust uses a combination like this, for example). In that case, if we see "'abc" we have to read the next character to see if it is `'abc'` or `'abc `. In the latter case, the ` ` is part of the next token, so we have to buffer it up for later.

**Comment by nikomatsakis** [comment]
(I guess not the best example, since in that one, only one character is needed, but in the limit you could need any number of characters buffered up.)

**Comment by Binero** [comment]
Good point, thanks.

**Comment by nikomatsakis** [comment]
I'm going to close this issue. The lexer is currently using the `Regex` library, and I think it only operates over `&str`, so this would be quite tricky to implement. :/

@Binero I'd recommend writing a custom lexer for this use case.
