### ISSUE TITLE
A rule with the "funky expression" <> doesn't work

### ISSUE THREAD

**Issue by joris-r** [nikomatsakis/lalrpop#83]
The following grammar is accepted (with v0.9.0) and leads to a parser with a syntax error.

```
grammar;
pub Component : (&'input str,&'input str) = Number Number => <>;
Number = r"[0-9]+";
```

I was expected the same result than with
`pub Component : (&'input str,&'input str) = <a:Number> <b:Number> => (a,b);`
but maybe I misinterpreted the tutorial document... In any case I don't think the generation of a erroneous rust source code is normal.

**Comment by nikomatsakis** [comment]
I think you need `(<>)`. We could fix this particular case (and fix the tutorial...) but in general the generation of action code is based on textual substitution so it is possible to generate rust code that will not parse. 
On Feb 19, 2016 17:14, Joris Rehm <notifications@github.com> wrote:The following grammar is accepted (with v0.9.0) and leads to a parser with a syntax error.

grammar;
pub Component : (&'input str,&'input str) = Number Number => <>;
Number = r"[0-9]+";


I was expected the same result than with
pub Component : (&'input str,&'input str) = <a:Number> <b:Number> => (a,b);
but maybe I misinterpreted the tutorial document... In any case I don't think the generation of a erroneous rust source code is normal.

**Comment by joris-r** [comment]
You're right: it's working with the parenthesis around.
It's not a very big deal for me, I just wanted to let you know.
