### ISSUE TITLE
self-hosting

### ISSUE THREAD

**Issue by nikomatsakis** [nikomatsakis/lalrpop#9]
Naturally, LALRPop should self-host. I think that's a good primary goal to work towards. Here is what is needed:

- [ ] write a tokenizer (#8)
- [ ] write the grammar
- [ ] explore the build infrastructure and get that up and running

I imagine that we can have a cargo package called something like "lalrpop-bootstrap" that is just a clone of a fixed version of lalrpop which we update periodically, and lalrpop can depend on that.

**Comment by pczarn** [comment]
In my own prototype, I added cargo packages with suffixes "-bootstrap", "-stage0", "-stage1", and "-stage2", in addition to the main package.

_-bootstrap_ defined a macro with a fixed expansion, which was previously generated expansion spliced into the main source file. _-stage0_ just invoked that macro. Each next "-stage_n_" just depended on the previous one, and used the main source file.

**Comment by pczarn** [comment]
All this is a lot like bootstrapping any compiler, of course.

I'm worried that expansion snapshots will skew code line counts and cause the git repo's size to grow over time. I think it's best to put them in a separate git repo.

**Comment by nikomatsakis** [comment]
So I actually already did this. What I did was make a "lalrpop-snap" package. I don't bother with all the stage0, stage1, etc. Seems to be working all right.
