### ISSUE TITLE
Improve error report about @L @R tokens

### ISSUE THREAD

**Issue by LukasKalbertodt** [nikomatsakis/lalrpop#90]
I just confused myself by creating a stupid grammar that would read two `@L` tokens successively. A minimal example:

```rust
grammar;

Spanned<T> = @L <T> @R;
Word: String = <s:r"[a-z]+"> => <>;

pub Foo = {
    Spanned<Word> "~",
    Spanned<Spanned<Word>> "+",
};
```

When having many macros like `Spanned`, it can easily happen to next two `Spanned` macros. The grammar above results in:

```
test.lalrpop:3:14: 3:15: Local ambiguity detected

  The problem arises after having observed the following symbols in the input:
    @L
  At that point, if the next token is a `r#"[a-z]+"#`, then the parser can
  proceed in two different ways.

  First, the parser could execute the production at
  src/grammar/test.lalrpop:3:14: 3:15, which would consume the top 0 token(s)
  from the stack and produce a `@L`. This might then yield a parse tree like
    ╷      ╷ Word  @R
    ├─@L───┘        │
    └─Spanned<Word>─┘

  Alternatively, the parser could shift the `r#"[a-z]+"#` token and later use it
  to construct a `Word`. This might then yield a parse tree like
    @L r#"[a-z]+"# @R
    │  └─Word────┘  │
    └─Spanned<Word>─┘

  See the LALRPOP manual for advice on making your grammar LR(1).
```

This is not really helpful right now (my real error message with my big grammar was even more confusing...). 

(the new error reporting is awesome though :3)

**Comment by LukasKalbertodt** [comment]
After thinking about it some more (and running into the same error again with my big grammar): why even report an error? I probably don't understand the `@L` `@R` tokens anyway -- why are these even considered real tokens? When replacing them with `"l"` and `"r"` in my example above, it works. Whats going on here? 

I think something like
```rust
Bar = Spanned<Word> "!" ";";
Foo = Spanned<Bar>;
```
should/could be allowed, right? But this kind of stuff fails, because the grammar requests two `@L` tokens... :confused:

**Comment by nikomatsakis** [comment]
@LukasKalbertodt I'm not sure I have the right setup, but let me explain why it is the way it is. Basically, reducing a `@L` or `@R` token reads the current location from the stream of tokens (`@L` reads the start of the next upcoming token, `@R` reads the end of the previous token) -- so the result is very dependent on when it executes. This is a bit counterintuitive but it yields the correct results and it also means we can allow you to insert `@L` and `@R` at arbitrary places in the grammar.

Another approach I had considered was to allow tokens (but not nonterminals) to be written like `@"foo"` -- this would then make the "value" of that token include its start/end span information (i.e., a three-tuple of `(L,V,R)` where `V` is the value of the terminal). If we set this up properly, it would never cause conflicts, but it would require a lot more "connecting" on the user's part. Basically you have to propagate the span information up from the individual tokens through any nonterminals by making it part of the value of a nonterminal.

I suppose yet another approach, one I did not consider, would be for me to ALWAYS propagate all span information for terminals and nonterminals. That is, I would implicitly produce a `(L, V, R)` for each nonterminal, and you would then be able to access that information via the `@L` "pseudo-symbols". This is probably the best of both worlds, though I think it would cost some overhead at parsing (likely minimal). I'd have to think about how it works with inlining, but it seems like it can be made to work. (One other tricky case is what "location" to produce for an empty nonterminal.)

Anyway, hope that helps explain what's going on. I'll think about implementing that final approach, I think that's probably the right thing to do. (And I could then remove `@L` vs `@R`, I guess, and just use a `@Foo` to get a "spanned" nonterminal, or `@(...)` for a group.)

**Comment by LukasKalbertodt** [comment]
Thanks a lot for the detailed explanation and sorry for my confusing problem description above (I clearly haven't finished thinking before I started writing :P).

Since I'm not completely sure, if I understood correctly: does this mean that the grammar can't request two `@L` tokens in consecutively? The grammar I'm working on produces an AST that contains a lot spans; particularly it also contains nodes that contain span information as well as other nodes also storing span information. I am talking about something like that (in lalrpop syntax):

```rust
ChildA = "a";
ChildB = Spanned<"b">;
ParentHelper = ChildB ChildA;
pub Parent = Spanned<ParentHelper>;
```
The parse tree of this grammar could look like this:
```
@L  @L "b"     @R    "a" @R
|   |          |     |   |
|   |          |     |   |
|   +- ChildB -+     |   |
|   |                |   |
|   +- ParentHelper -+   |
|                        |
+-------- Parent --------+
```
So this parse tree is impossible in lalrpop, because two `@L` tokens can't be read in sequence? How about just *not* consuming position tokens after they have been read? One could read the same position token multiple times then.

------

I'm probably not able to make a qualified comment, what I think is the best solution for `lalrpop`'s future -- but of course the last one sounds nice. I always thought of `@L` and `@R` as pseudo symbols anyway.

**Comment by nikomatsakis** [comment]
It is fine to have two @L in sequence. Reducing an @L doesn't consume
any tokens -- it just reads from the current value of the position
information and pushes the reuslt onto the parser's internal stack.

**Comment by LukasKalbertodt** [comment]
I'm afraid, I still don't understand :/ 

This minimalistic grammar:
```rust
pub Foo = {
    @L <"a"> @R,
    <"a"> "x",
};
```
doesn't work:
```
Conflict detected

    when in this state:
  @L = (*) ["a"]
  Foo = (*) @L "a" @R [EOF]
  Foo = (*) "a" "x" [EOF]
  __Foo = (*) Foo [EOF]

  and looking at a token `"a"` we can reduce to a `@L` but we can also shift
```

When removing the position tokens, everything is fine. Why exactly doesn't this work? And how can I resolve these problems? Generally speaking, I think this problem always occurs when the same symbol (terminal or non-terminal) can either be read with or without preceding `@L` token.

**Comment by nikomatsakis** [comment]
The easiest way to make it work would be to add @L tokens at the same point in both productions.

**Comment by nikomatsakis** [comment]
Will write more tomorrow.

**Comment by nikomatsakis** [comment]
(That said I would like to improve situation here)

**Comment by sfackler** [comment]
I'm running into a variant of this as well. Removing the span references from Expression2 will allow it to compile but I haven't figured out how to get it to work without doing that. Here's a minimized version:

```
grammar;

pub Expression2: () = {
    @L Expression2 Expression2Op Expression1 @R => (),
    @L Expression1 @R => (),
};

Expression2Op: () = {
    @L "*" @R => (),
};

Expression1: () = {
    @L "(" Expression2 ")" @R => (),
};
```

```
/Users/sfackler/test/src/parser.lalrpop:4:5: 4:6: Local ambiguity detected

  The problem arises after having observed the following symbols in the input:
    @L @L
  At that point, if the next token is a `"("`, then the parser can proceed in
  two different ways.

  First, the parser could execute the production at
  /Users/sfackler/test/src/parser.lalrpop:4:5: 4:6, which would consume the top
  0 token(s) from the stack and produce a `@L`. This might then yield a parse
  tree like
    ╷    ╷ Expression1 @R
    ├─@L─┘              │
    └─Expression2───────┘

  Alternatively, the parser could shift the `"("` token and later use it to
  construct a `Expression1`. This might then yield a parse tree like
    @L @L "(" Expression2 ")" @R @R
    │  └─Expression1───────────┘  │
    └─Expression2─────────────────┘

  See the LALRPOP manual for advice on making your grammar LR(1).
```

**Comment by nikomatsakis** [comment]
So, I actually think this won't be that hard to fix such that one can insert `@L` and `@R` tokens wherever one wants. I got maybe 50% of the way through on the subway ride this morning. In the meantime, however, @sfackler you can solve your problem in various ways, but the way I would prefer is to basically push the `@L` and `@R` tokens down to the "lowest levels" of your hierarachy, so basically where there are actual symbols. If you need to extract position information at a higher level, you would extract it from the nonterminals. As shown here:

```
grammar;

pub Expression2: () = {
    // I removed @L and @R here. To get those values, take the start position of
    // Expression2 and the end position of Expression1.
    Expression2 Expression2Op Expression1 => (),
    Expression1 => (),
};

Expression2Op: () = {
    @L "*" @R => (),
};

Expression1: () = {
    @L "(" Expression2 ")" @R => (),
};
```

(Essentially this is what my branch would do as well, except it would be automated.)

**Comment by nikomatsakis** [comment]
(I also decided to keep the user interface as `@L` and `@R` rather than making a "spanned" combinator, though that'd be easy enough to change if we wanted. It's kind of orthogonal. Curious to hear what people think would be more convenient in practice.)

**Comment by LukasKalbertodt** [comment]
Do I understand correctly that you are working on the position token system, such that some (all?) of the problems above will be solved?

-----

I tried to adjust my grammar with the information in this "thread", however I found an example where it's not really possible. At least as far as I understand... which is not very far currently. I hope this example helps with understanding the problem rather than being unnecessary or confusing...

Suppose we want to parse standard left associative binary operations and want to save the result in an AST like 
```rust
struct Expr {
    inner: ExprType,
    span: (usize, usize),
}

enum ExprType {
    Add(Box<Expr>, Box<Expr>),
    Num(i32),
}
```
(we want to save spans for all sub expressions).

Our grammar would look like
```rust
Num: i32 = "1" => 1;

Plus: ExprType = {
    Num => ExprType::Num(<>),
    <ll: @L> <lhs: Plus> <lr: @R> "+" <rl: @L> <rhs: Num> <rr: @R> => ExprType::Add (
        Box::new(Expr { inner: lhs, span: (ll, lr) }),
        Box::new(Expr { inner: rhs, span: (rl, rr) }),
    ),
};

pub Expr: Expr = {
    <l: @L> <inner: Plus> <r: @R> => Expr { inner: inner, span: (l, r) },
    <l: @L> <inner: Num> <r: @R> => Expr { inner: inner, span: (l, r) },
};
```

And this grammar won't work. The recursion within `Plus` in the beginning means that we could in theory read as many `@L` tokens as we want. lalrpop says:

```
Local ambiguity detected

  The problem arises after having observed the following symbols in the input:
    @L
  At that point, if the next token is a `"1"`, then the parser can proceed in
  two different ways.

  First, the parser could execute the production at
  src/grammar/test.lalrpop:29:10: 29:11, which would consume the top 0 token(s)
  from the stack and produce a `@L`. This might then yield a parse tree like
    ╷    ╷ Plus @R "+" @L Num @R
    ├─@L─┘                     │
    └─Plus─────────────────────┘

  Alternatively, the parser could shift the `"1"` token and later use it to
  construct a `Num`. This might then yield a parse tree like
    @L "1"    ╷ @R
    │  ├─Num──┤  │
    │  └─Plus─┘  │
    └─Expr───────┘

  See the LALRPOP manual for advice on making your grammar LR(1).
```
-----
How would one solve this problem?

**Comment by nikomatsakis** [comment]
> Do I understand correctly that you are working on the position token system, such that some (all?) of the problems above will be solved?

Yes.

> I tried to adjust my grammar with the information in this "thread", however I found an example where it's not really possible. At least as far as I understand... which is not very far currently. I hope this example helps with understanding the problem rather than being unnecessary or confusing...

Your grammar example confuses me a bit. It seems ambiguous. For example, if we strip out all the position information, we get this:

```
Num: i32 = "1" => 1;

Plus: ExprType = {
    Num => ExprType::Num(<>),
    <ll: @L> <lhs: Plus> <lr: @R> "+" <rl: @L> <rhs: Num> <rr: @R> => ExprType::Add (
        Box::new(Expr { inner: lhs, span: (ll, lr) }),
        Box::new(Expr { inner: rhs, span: (rl, rr) }),
    ),
};

pub Expr: Expr = {
    <l: @L> <inner: Plus> <r: @R> => Expr { inner: inner, span: (l, r) },
    <l: @L> <inner: Num> <r: @R> => Expr { inner: inner, span: (l, r) },
};
```

we can parse `Num` in two ways, either as an `Expr` or as a `Plus`. 

Which yields the following error (which really ought to be fixed):

```
/Users/nmatsakis/tmp/issue-90k.lalrpop:6:5: 6:31: Conflict detected

    when in this state:
  Expr = Num (*) [EOF]
  Plus = Num (*) [EOF]
  Plus = Num (*) ["+"]

  and looking at a token `EOF` we can reduce to a `Plus` but we can also reduce
  to a `Expr`
```

But I THINK what you wanted is vaguely like this:

```
grammar;

Num: i32 = "1" => 1;

Atom: Expr = {
    <l:@L> <n:Num> <r:@R> => Expr { inner: ExprType::Num(n), span: (l, r) }
};

Plus: Expr = {
    Atom,
    <lhs: Plus> "+" <rhs: Atom> => Expr {
        inner: ExprType::Add(lhs, rhs),
        span: (lhs.span.0, rhs.span.1), // <-- Here!
    ),
};

pub Expr: Expr = {
    Plus,
};
```

Note that to get the span for `a + b` I extracted the span information that was already present in the embedded expressions.

**Comment by sfackler** [comment]
Thanks for the advice with only grabbing `@L`s and `@R`s next to the lowest levels - things seem to be working now!

**Comment by LukasKalbertodt** [comment]
@nikomatsakis Yes! Sorry, my bad -- I thought I tested my code. Your last code block is pretty much what I wanted to say. Btw: I think you made a copy-paste mistake in your first code block (exactly my code from above).

And I understand that one can pull position information from the expressions further down. My point is: if you have a big grammer and a big AST, it's very nice to have a lot of abstractions (like `Spanned`). And pulling out position information for nearly every non-terminal is something I really don't want to do.

But I will be quiet now and hope that everything will magically work, after you're finished with this (maybe in the subway ride tomorrow :P)
